services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: academy-backend
    secrets:
      - pg-passwd
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - DB_PASSWORD_FILE=/run/secrets/pg-passwd
      - DB_NAME=academy
      - DB_CHARSET=utf8
      - DB_TIMEZONE=UTC
      - DB_SECURE=false
      - DB_UNIX_SOCK=
      - DB_DRIVER=postgres
    expose:
      - 8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    user: postgres
    container_name: academy-postgres-db
    secrets:
      - pg-passwd
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg-passwd
      - POSTGRES_DB=academy
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx
    container_name: academy-nginx
    volumes:
      - type: bind
        source: ./config/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8000:80
    depends_on:
      - backend

volumes:
  pg-data:

secrets:
  pg-passwd:
    file: config/db/postgres/passwd.txt
